// Enchanted jewellery (the magic plan, stage A5c): which piece each plain one becomes under an enchanting spell,
// and what the four special pieces and the two rubbed ones do (world.ts runs them). Everything else an enchanted
// piece does is its worn bonus, in items.ts. Generated by scratch/tmp/enchant-gen.mjs; the plan's §2.5b says why.
import type { RuneKey } from "./spells.ts";

/** A plain piece's enchanted self, by item key. */
export const ENCHANTED: Readonly<Record<string, string>> = {
  opal_ring: "hunters_ring",
  opal_necklace: "nimble_necklace",
  opal_bracelet: "quick_bracelet",
  opal_amulet: "amulet_of_plenty",
  jade_ring: "homing_ring",
  jade_necklace: "wayfinders_necklace",
  jade_bracelet: "masons_bracelet",
  jade_amulet: "brewers_amulet",
  topaz_ring: "ring_of_mercy",
  topaz_necklace: "devout_necklace",
  topaz_bracelet: "trackers_bracelet",
  topaz_amulet: "ember_amulet",
  sapphire_ring: "ring_of_thorns",
  sapphire_necklace: "travellers_necklace",
  sapphire_bracelet: "potters_bracelet",
  sapphire_amulet: "mages_amulet",
  emerald_ring: "duellists_ring",
  emerald_necklace: "knotted_necklace",
  emerald_bracelet: "siege_bracelet",
  emerald_amulet: "wardens_amulet",
  ruby_ring: "forge_ring",
  ruby_necklace: "diggers_pendant",
  ruby_bracelet: "warded_bracelet",
  ruby_amulet: "amulet_of_might",
  diamond_ring: "lifeward_ring",
  diamond_necklace: "rekindling_necklace",
  diamond_bracelet: "deepwalkers_bracelet",
  diamond_amulet: "amulet_of_the_four",
  wyrmstone_ring: "ring_of_plenty",
  wyrmstone_necklace: "crafters_necklace",
  wyrmstone_bracelet: "fighters_bracelet",
  wyrmstone_amulet: "wyrm_amulet",
  onyx_ring: "stone_ring",
  onyx_necklace: "raging_necklace",
  onyx_bracelet: "mending_bracelet",
  onyx_amulet: "night_amulet",
  sunstone_ring: "ring_of_endurance",
  sunstone_necklace: "keen_necklace",
  sunstone_bracelet: "grim_bracelet",
  sunstone_amulet: "sun_amulet",
};

/** The pieces that do something when a blow lands: return part of it, take the wearer home, or heal them, each once or for a while. */
export type Special = "thorns" | "lifeward" | "rekindle";
export const SPECIAL: Readonly<Record<string, Special>> = {
  ring_of_thorns: "thorns",
  lifeward_ring: "lifeward",
  rekindling_necklace: "rekindle",
};

/** How much a Ring of Thorns returns before it crumbles: forty, the reference's. */
export const THORNS_CHARGE = 40;
/** Where a rubbed piece can take its wearer, by the teleport spell whose landing it uses; and how long before it answers again (milliseconds, saved). */
export const RUBS: Readonly<Record<string, readonly string[]>> = {
  homing_ring: ["oakridge_teleport"],
  wyrm_amulet: ["oakridge_teleport", "brinehaven_teleport", "kilnhold_teleport", "deepdelve_teleport"],
};
export const RUB_WAIT_MS = 10 * 60 * 1000;

// --- Enchanted arrows (the magic plan, stage A5d) ------------------------------------------------------

/**
 * Enchant Arrows: one spell, as the reference's bolt enchantments are one icon, working ten gem-tipped arrows
 * a cast. For each, the level, recipe and XP the reference asks for that gem's bolts (its cosmic the Star rune),
 * and what they become. The reference's pearl has no pearl here, so nine, not ten.
 */
export const ARROW_ENCHANTS: Readonly<Record<string, { level: number; runes: ReadonlyArray<readonly [RuneKey, number]>; xp: number; into: string }>> = {
  opal_tipped_arrow: { level: 4, runes: [["gale_rune", 2], ["star_rune", 1]], xp: 90, into: "enchanted_opal_arrow" },
  sapphire_tipped_arrow: { level: 7, runes: [["tide_rune", 1], ["thought_rune", 1], ["star_rune", 1]], xp: 175, into: "enchanted_sapphire_arrow" },
  jade_tipped_arrow: { level: 14, runes: [["stone_rune", 2], ["star_rune", 1]], xp: 190, into: "enchanted_jade_arrow" },
  emerald_tipped_arrow: { level: 27, runes: [["gale_rune", 3], ["star_rune", 1], ["bloom_rune", 1]], xp: 370, into: "enchanted_emerald_arrow" },
  topaz_tipped_arrow: { level: 29, runes: [["ember_rune", 2], ["star_rune", 1]], xp: 330, into: "enchanted_topaz_arrow" },
  ruby_tipped_arrow: { level: 49, runes: [["ember_rune", 5], ["star_rune", 1], ["heart_rune", 1]], xp: 590, into: "enchanted_ruby_arrow" },
  diamond_tipped_arrow: { level: 57, runes: [["stone_rune", 10], ["star_rune", 1], ["oath_rune", 2]], xp: 670, into: "enchanted_diamond_arrow" },
  wyrmstone_tipped_arrow: { level: 68, runes: [["stone_rune", 15], ["star_rune", 1], ["shade_rune", 1]], xp: 780, into: "enchanted_wyrmstone_arrow" },
  onyx_tipped_arrow: { level: 87, runes: [["ember_rune", 20], ["star_rune", 1], ["grave_rune", 1]], xp: 970, into: "enchanted_onyx_arrow" },
};
/** How many arrows one cast works. */
export const ARROWS_A_CAST = 10;

/**
 * What an enchanted arrow does now and then, at the reference's chance for its gem's bolts, in this game's
 * terms where the reference's needs a system this game has not got: opal's strike adds a tenth of Ranged;
 * sapphire's gives the shooter a prayer point (a creature has none to drain); jade's grips the creature for
 * three ticks; emerald's stings for one more (there is no poison); topaz's lowers Strength 5%; ruby's takes a
 * fifth of what the creature has left (at most 100) for a tenth of what the shooter has; diamond's lands
 * through any defence and hits 15% harder; wyrmstone's burns for a fifth of Ranged; onyx's hits a fifth harder
 * and heals the shooter a quarter of it.
 */
export type ArrowProc = "lucky" | "clear" | "grip" | "sting" | "flare" | "blood" | "pierce" | "breath" | "drink";
export const ARROW_PROCS: Readonly<Record<string, { chance: number; proc: ArrowProc }>> = {
  enchanted_opal_arrow: { chance: 0.05, proc: "lucky" },
  enchanted_sapphire_arrow: { chance: 0.05, proc: "clear" },
  enchanted_jade_arrow: { chance: 0.06, proc: "grip" },
  enchanted_emerald_arrow: { chance: 0.55, proc: "sting" },
  enchanted_topaz_arrow: { chance: 0.04, proc: "flare" },
  enchanted_ruby_arrow: { chance: 0.06, proc: "blood" },
  enchanted_diamond_arrow: { chance: 0.1, proc: "pierce" },
  enchanted_wyrmstone_arrow: { chance: 0.06, proc: "breath" },
  enchanted_onyx_arrow: { chance: 0.11, proc: "drink" },
};
