// Enchanted jewellery (the magic plan, stage A5c): which piece each plain one becomes under an enchanting spell,
// and what the four special pieces and the two rubbed ones do (world.ts runs them). Everything else an enchanted
// piece does is its worn bonus, in items.ts. Generated by scratch/tmp/enchant-gen.mjs; the plan's §2.5b says why.

/** A plain piece's enchanted self, by item key. */
export const ENCHANTED: Readonly<Record<string, string>> = {
  opal_ring: "hunters_ring",
  opal_necklace: "nimble_necklace",
  opal_bracelet: "quick_bracelet",
  opal_amulet: "amulet_of_plenty",
  jade_ring: "homing_ring",
  jade_necklace: "wayfinders_necklace",
  jade_bracelet: "masons_bracelet",
  jade_amulet: "brewers_amulet",
  topaz_ring: "ring_of_mercy",
  topaz_necklace: "devout_necklace",
  topaz_bracelet: "trackers_bracelet",
  topaz_amulet: "ember_amulet",
  sapphire_ring: "ring_of_thorns",
  sapphire_necklace: "travellers_necklace",
  sapphire_bracelet: "potters_bracelet",
  sapphire_amulet: "mages_amulet",
  emerald_ring: "duellists_ring",
  emerald_necklace: "knotted_necklace",
  emerald_bracelet: "siege_bracelet",
  emerald_amulet: "wardens_amulet",
  ruby_ring: "forge_ring",
  ruby_necklace: "diggers_pendant",
  ruby_bracelet: "warded_bracelet",
  ruby_amulet: "amulet_of_might",
  diamond_ring: "lifeward_ring",
  diamond_necklace: "rekindling_necklace",
  diamond_bracelet: "deepwalkers_bracelet",
  diamond_amulet: "amulet_of_the_four",
  wyrmstone_ring: "ring_of_plenty",
  wyrmstone_necklace: "crafters_necklace",
  wyrmstone_bracelet: "fighters_bracelet",
  wyrmstone_amulet: "wyrm_amulet",
  onyx_ring: "stone_ring",
  onyx_necklace: "raging_necklace",
  onyx_bracelet: "mending_bracelet",
  onyx_amulet: "night_amulet",
  sunstone_ring: "ring_of_endurance",
  sunstone_necklace: "keen_necklace",
  sunstone_bracelet: "grim_bracelet",
  sunstone_amulet: "sun_amulet",
};

/** The pieces that do something when a blow lands: return part of it, take the wearer home, or heal them, each once or for a while. */
export type Special = "thorns" | "lifeward" | "rekindle";
export const SPECIAL: Readonly<Record<string, Special>> = {
  ring_of_thorns: "thorns",
  lifeward_ring: "lifeward",
  rekindling_necklace: "rekindle",
};

/** How much a Ring of Thorns returns before it crumbles: forty, the reference's. */
export const THORNS_CHARGE = 40;
/** Where a rubbed piece can take its wearer, by the teleport spell whose landing it uses; and how long before it answers again (milliseconds, saved). */
export const RUBS: Readonly<Record<string, readonly string[]>> = {
  homing_ring: ["oakridge_teleport"],
  wyrm_amulet: ["oakridge_teleport", "brinehaven_teleport", "kilnhold_teleport", "deepdelve_teleport"],
};
export const RUB_WAIT_MS = 10 * 60 * 1000;
